server:
  port: ${PORT:8080}   # Render injects PORT; 8080 locally

spring:
  application:
    name: portfolio1
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
